.github/workflows/mistserver.yaml

Create releases for mistserver on tag push of the form: `mist-v*` where `v*` is the semver specification.

workflow: Create workflow manifest for compiling mistserver

---

Makefile
README.md

Changes:
- Use the flag `-DCMAKE_OSX_ARCHITECTURES=arm64` with all cmake commands which seemed to fix the "x86 linking with arm64" warnings/errors in my M1 builds. Strangely, I seem to be the only person on M1 that has run into this thus far so there might be something unique about my environment. I have **not** tested these changes on x86 (i.e. non-M1 Apple) so if someone with access to that architecture can test that out that would be much appreciated
- Added task-runner as a dependency in the README. Without it `make` will fail
- Added go1.17 as a recommendation in the README as go1.16 will cause build errors on arm64

Fix OSX M1 build

---

cmd/catalyst-node/catalyst-node.go

catalyst-node: populate MistUtilLoad with hostnames instead of ip-addr

---

cmd/catalyst-node/catalyst-node.go
test/e2e/e2e_test.go
test/e2e/mist_config.go

Add support for tags while forming the Catalyst cluster. It will to set up bootstrap serf nodes which will not be used for Mist load balancing. Additionally, it allows to set up two separate Catalyst clusters using the same Serf cluster.
fix https://github.com/livepeer/livepeer-infra/issues/885

Add serf tags to enable bootstrap catalyst nodes

---

Dockerfile
cmd/downloader/bucket/bucket.go
cmd/downloader/github/github.go
cmd/downloader/github/github_test.go
cmd/downloader/types/types.go

This helps in negating docker cache; especially useful for bucket strategy builds.

Use `commit` info to populate inside manifest

---

.drone.yaml
Dockerfile
test/copy-mist-binaries.sh
test/e2e/e2e_test.go

Use MistLoadTest to spawn multiple clients for a specific protocol (e.g. HLS) as viewers at catalyst-two node. The test passes if every client is able to connect and stream successfully. The json files generated by MistLoadTest are parse to verify if streams passed or failed.

e2e_test: integrate MistLoadTest to verify streaming

---

cmd/downloader/manifest/manifest.go

This should resolve empty webhook triggers which don't pick changes to upstream project releases.

manifest.go: Use `latest` as default release name when fetching github releases

---

Makefile
manifest.yaml

Added `bin/` dir to PATH for `dev` target, because otherwise Mist can't find `livepeer-catalyst-uploader` binary. Should we update binary discovery in Mist?

S3 output support: add catalyst-uploader binary

---

.github/workflows/test.yaml
cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go
config/catalyst-one.json
config/catalyst-two.json
test/e2e/mist_config.go

Fixes #95 and livepeer/livepeer-infra#894

catalyst-node: Add `redirectPrefixes` support when querying mist

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go

I'm kind of unhappy with the messiness of this; in particular returning both a URL and an error from the `queryMistForClosestNode()` function is kind of smelly. I at least tried to thoroughly-comment all the confusing cases of "we didn't find the stream but return the server anyway" kind of thing.

catalyst-node: add support for /json_prefix+stream.js urls, 404 handling

---

cmd/downloader/bucket/bucket.go
go.mod

This would allow for finer version control on released binaries. Currently, the downloads are always done for most 'recent' commit available for a branch in `bucket` strategy. This led to and old issue #110 
With the change here, the commit SHA (if present in `manifest.yaml`) would be the default value to download.

bucket.go: Use commit hash provided in manifest over current value

---

cmd/downloader/bucket/bucket.go
manifest.yaml

Part of work wrt: https://github.com/livepeer/livepeer-infra/issues/917
Fixes livepeer/livepeer-infra#917

manifest.yaml: Use bucket strategy to download projects

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go

A bunch of changes as we close in on the production deployment:
* Add `-advertise`, allowing catalyst-node to advertise an IP address that it's not actually binding to (needed for Kubernetes `hostPort` support)
* Add `-mist-load-balancer-template`, allowing us to specify alternate ports for Mist to query nodes. (needed for running Canary stuff on `:20443`)
* https://github.com/livepeer/catalyst/pull/150/commits/32be8fdb18513e27da12f8782251b2ae810c13a1, which checks `media=true` nodes for the load balancer (instead of matching the local node's tags)
* Added the ability for nodes to specify `http`, `https`, and `dtsc` tags, specifying non-default ports and hosts for connections. We're using this for the new rollout system; a new set of Catalyst pods can roll out on the same IPs with DTSC …

catalyst-node: changes for production release

---

cmd/downloader/manifest/manifest.go
manifest.yaml

Set indent level to 2 when updating manifest, following configuration from `.editorconfig`

Use yaml encoder for controlled marshalling of manifest data.

---

Dockerfile.local
Makefile

I forgot about this trick to work around `.dockerignore` until now!
This will be useful for devs making changes to other projects locally but then testing with the containerized version.

Makefile: add Dockerfile.local build

---

cmd/catalyst-node/catalyst-node.go
cmd/livepeer-log/livepeer-log.go

This allows `VM_` parameters to configure everything via environment variables, meaning we don't have to add all the VM options to livepeer-log.

vmagent/victoriametrics: add environment variable config

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go

Needed for things like `audio=false` to work properly.

catalyst-node: redirect query parameters on nodeHost redirect

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go

One more place where we need to redirect query parameters.

catalyst-node: properly redirect query parameters

---

cmd/catalyst-node/catalyst-node.go

Workaround for https://github.com/DDVTECH/mistserver/issues/114

catalyst-node: use chunked encoding for stream triggers

---

cmd/catalyst-node/handlers/access-control/access-control.go
cmd/catalyst-node/handlers/access-control/access-control_test.go

Turns out the stale cache refreshing in background was really not working, as the check done from inside the goroutine was actually checking if the entry was fully expired instead of checking if it is stale.

access-control: Fix stale cache test

---

cmd/catalyst-node/catalyst-node.go

**catalyst-node: update string prefix matches for various vod sources**
For vod sources, the SOURCE_STREAM trigger's response from catalyst-api
must be an empty field so that Mist uses the values configured in the
source field.
For /api/vod endpoint, source streams are added as catalyst_vod_*
prefix.
For /api/transcode/file endpoint, source streams are added as tr_src_*
prefix.
Check both prefixes and return with empty response body to Mist.

catalyst-node: update string prefix matches for various vod sources

---

test/e2e/vod_test.go

I tried to stand up a local HTTP server in the tests to catch callbacks, which would then let us wait on a "segmenting complete" callback rather than checking the number of files. This proved tricky though, because Catalyst is running in a container here and so can't reach a local HTTP endpoint outside that container.

Allow E2Es to handle new async VOD upload flow

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go

This avoids the 500 error we've been seeing a lot.

catalyst-node: crash on serf failures

---

manifest.yaml

ffprobe does not seem to be installed on the pods yet meaning vod jobs are failing, roll back for now

revert to previous catalyst-api

---

test/e2e/vod_test.go

The "split" var that we now pass to Mist (set to 5) contains the minimum duration of segments in seconds. 
5 = 5000, which means the first possible split is at 5001. If the keyframes are at every exact whole integer like in the test video we use then the closest cutting point > 5000 is 6000

Update test assertion to reflect new Mist segmenting logic

---

Dockerfile

We need a nodejs script in order to upload files into web3.storage.
It increases the Docker images size `2.22GB` => `2.46GB`
For the context, please check this PR: https://github.com/livepeer/go-tools/pull/17
fix https://github.com/livepeer/catalyst/issues/373

Add livepeer-w3 to catalyst docker image

---

manifest.yaml

should dump `livepeer-mist-bigquery-uploader` (but might fail for arm64)

manifest.yaml: Add mist-bigquery-uploader to final catalyst build

---

cmd/livepeer-log/livepeer-log.go
cmd/livepeer-log/livepeer-log_test.go
cmd/livepeer-log/log_spam_test.sh
go.mod
go.sum

We were previously using `bufio.Scanner` that stops scanning when it hits a line too long. We don't want that. `bufio.Reader` does what we want.

livepeer-log: handle log lines longer than 64k

---

.github/workflows/build.yaml

It's faster. [4m42s](https://github.com/livepeer/catalyst/actions/runs/4874482388/jobs/8695477165) down from [9m32s](https://github.com/livepeer/catalyst/actions/runs/4874239090).

ci: cross-compile livepeer-log and catalyst

---

manifest.yaml
test/e2e/e2e_test.go

Temp revert of git shas to be able to roll out a mist config change before code changes

Temp revert of git shas

---

manifest.yaml

Unblocking deployment of the other services in Catalyst. This SHA is the version currently running on Prod.

Pin Mist to known good version

---

.github/workflows/catalyst.yaml

Currently, build notifications are sent after each successful docker image publish event. This leads to multiple github workflows being run and cancelled in quick successions with no real gains.

docker: Trigger build notifications just once

---

manifest.yaml

This is failing for catalyst-api reasons, so I'm bumping go-livepeer to unblock @ecmulli https://github.com/livepeer/catalyst/pull/625

bump go-livepeer (and not catalyst-api)

---

.github/workflows/staging.yaml

Two changes:
1. Add a `staging-generator` branch that rebuilds the staging manifest on push for the purpose of testing this without constantly pushing to `main`
2. Hardcodes `GIT_COMMITTER_DATE` and `GIT_AUTHOR_DATE` so they're deterministic and we stop getting this:
I don't know why that's happening; the "don't push if there aren't any changes" rule was either broken by https://github.com/livepeer/catalyst/commit/1967fcb74e37b862dafb4d7f60439954845f394f or by https://github.com/livepeer/catalyst/commit/7b360973c032af16727afebc3adc3cabf8fc425b. 
The downside to this is that the dates on the automerge commits will be wrong and that's annoying. An alternative would be to query the last-modified times on all the bucket files and use the latest of them:
```
curl --head --silent …
```

ci: fixes to the staging manifest generator

---

Dockerfile

The proper solution is to implement this: https://github.com/contentauth/c2patool/issues/149
In the meantime, however, since our build currently takes crazy ~1.5h, I added this hack to download c2patool from our own binaries instead of building it from sources. It's not too elegant, but speeds up our build CI significantly.

Speed up Catalyst build by not building c2patool from source

---

.github/workflows/build.yaml

So that inplace deploys work properly.

ci: kick off update piplines when a binary build completes

---

.github/workflows/build.yaml
Dockerfile

Speed up Catalyst build by downloading c2patool binary (instead of building it from source)

Speed up Catalyst build by downloading c2patool binary

---

manifest.yaml

MistServer would need to be manually updated.

[ENG-1889] manifest: Skip manifest updation for mistserver releases

---

manifest.yaml

https://linear.app/livepeer/issue/ENG-1660/mist-to-stop-restarting-catalyst-api-and-livepeer-connectors-on-usr1

manifest.yaml - update mistserver

---

manifest.yaml

For staging, this include:
- unrevert of commits after the multistream rollback
- [transcode,video: Add support for copying HLS input segments (](https://github.com/livepeer/catalyst-api/commit/c31e2b5549402e88a1daf067e7f391a35d2bc956)https://github.com/livepeer/catalyst-api/pull/1261[)](https://github.com/livepeer/catalyst-api/commit/c31e2b5549402e88a1daf067e7f391a35d2bc956)
- [access-control: use whole acReq payload as cacheKey (](https://github.com/livepeer/catalyst-api/commit/cb6dce39167a66c2b31cf7cb7307a9d85c65173a)https://github.com/livepeer/catalyst-api/pull/1267[)](https://github.com/livepeer/catalyst-api/commit/cb6dce39167a66c2b31cf7cb7307a9d85c65173a)

manifest: update catalyst-api version commit

---

Dockerfile

This is to fix a segmenting bug identified by Josh in https://linear.app/livepeer/issue/PS-551/vod-issues-cannot-play-asset as being fixed in version 7, whereby segments beyond the first one are missing SPS/PPS values and so aren't independently decodable (which then breaks VOD transcoding).

Bump ffmpeg version from 6 -> 7

---

.github/workflows/build.yaml

Always use the mist with debug symbols.
Related to https://github.com/livepeer/livepeer-infra/pull/2487
[Discord discussion](https://discord.com/channels/423160867534929930/1308533447056293889/1308740397840728084)

Don't strip debug symbols
