livepeer/catalyst

.github/workflows/catalyst.yaml

Add `ghcr.io` docker image publishing.

---

test/e2e/e2e_test.go

Bare minimum test case that reproduces this error: 
```
[2022-08-02 18:41:29] MistOutHLS:video+b0dcxvwml48mxt2s (490) INFO: Shared metadata not ready yet - no tracks valid (/tmp/drone-7pq2c6BO3H9JHJZs/drone/src/lib/dtsc.cpp:2151) 
``` 
Can be invoked by: 
``` 
go test -v test/e2e/* -run="Interrupt" --logtostderr
```
Fix \#86

e2e_test: add new test to detect stream interruption failures

---

cmd/livepeer-log/livepeer-log.go
config/mistserver.dev.conf
config/scrape_config.yaml
manifest.yaml

this is required to export logs to the remote victoria-metrics clusters we have

Add vmagent to manifest, better scrape_configs

---

cmd/catalyst-node/catalyst-node.go

catalyst-node: flip source query conditional

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/catalyst-node_test.go

Add support for the segment in the playback path. For example, `https://playback.livepeer.fun/hls/5797b1te5y6au14l/0_1/index.m3u8`
Before we only supported a path without segments, for example, `https://playback.livepeer.fun/hls/5797b1te5y6au14l/index.m3u8`.
That broke our loadtester and record-tester.
fix https://github.com/livepeer/livepeer-infra/issues/927

Add support for segments in the redirection mechanism

---

.drone.yaml
.github/workflows/catalyst.yaml
Dockerfile
Makefile

Reduces the final docker image size.

Dockerfile: Create stages to strip binaries off debug symbols.

---

.github/workflows/build.yaml
.github/workflows/test.yaml
go.mod
go.sum

- generate/download all binaries inside the workflow
- strip debug symbols off (reduce file size)
- archive
- upload to gcp storage

build.yaml: Add a build workflow to project

---

Dockerfile

Useful to do in-place upgrades using Ansible.

Dockerfile: add python (for ansible)

---

.drone.yaml
test/e2e/vod_test.go

These have changed since the test was written, which is why it was failing.

Check for correct segmenting output paths in VOD E2E

---

Dockerfile

Fix https://github.com/livepeer/catalyst-api/issues/364

Dockerfile: install ffmpeg

---

.github/workflows/build.yaml
.github/workflows/catalyst.yaml

ci: properly use ids from pull request head

---

Dockerfile

Needed for the web3.storage integration

Add ipfs-car CLI

---

cmd/catalyst-node/catalyst-node.go
cmd/catalyst-node/handlers/access-control/access-control.go
cmd/catalyst-node/handlers/access-control/access-control_test.go

We need to make some changes to this to support accessKey gating (as well as jwt) so this is an inital refactor to tidy things up a bit to make the further changes easier.

Small refactor to access-control

---

cmd/catalyst-node/handlers/access-control/access-control.go

This refactor is for the access control work, it allows us to hook into the `GetPlaybackAccessControlInfo` function and pass our own request body in (for accessKey rather than jwt).

Refactor access control to support forms of gating other than jwt

---

test/e2e/vod_test.go

Cleanup work after new Catalyst VOD API is deployed.

Update VOD Tests for new Catalyst API

---

Dockerfile
Dockerfile.local

Install gstreamer-tools and it's base/good/bad plugins.

[SRE-118] Dockerfile: Add gstreamer to base docker image with its plugins

---

test/e2e/e2e_test.go

Including some more information about why the tests failed, since we seem to get intermittent failures at this stage

Improve manifest check error message

---

manifest.yaml

Revert "[BOT] Update `manifest.yaml` for staging"

---

manifest.yaml

This reverts commit 0865e39943317aa83de5150dfd55a45cee0288e5.

Revert "Test Live Multistream in staging (#599)"

---

manifest.yaml

This reverts commit ff3e0ddd0481af0a0a91241405d507fd7c9bccc7.

Revert "[AUTO-COMMIT] Update `manifest.yaml` (#703)"

---

manifest.yaml

Files changed:
M	manifest.yaml

[AUTO-COMMIT] Update `manifest.yaml`

---

manifest.yaml

Update uploader and set catalyst-api to the version that's on prod.

Update uploader only

---

.github/workflows/build.yaml

build.yaml: Fix architecture when building tarball

---

Dockerfile

Dockerfile: --link isn't supported by buildah/podman

---

.github/workflows/catalyst.yaml
manifest.yaml

It's crashing on the new version.

Manifest: revert studio

---

.github/workflows/build.yaml

build.yaml: Revert `actions/upload-artifact` to v3

---

manifest.yaml

bump catalyst-api

---

.github/workflows/build.yaml
manifest.yaml

* transcode/transmux: set MP4 generation limit https://github.com/livepeer/catalyst-api/pull/1065
* serf messages - loglevel adjustments https://github.com/livepeer/catalyst-api/pull/1069
* log removal - https://github.com/livepeer/catalyst-api/pull/1070

manifest.yaml catalyst-api (logs and mp4)

---

.github/workflows/build.yaml

[Discord](https://discord.com/channels/423160867534929930/1006190767510917202/1194295236063662121)

build workflow - uninstall rustup before installing it

---

config/full-stack.json

Related to https://github.com/livepeer/studio/pull/2139 and https://github.com/livepeer/livepeer-infra/pull/2052

values: new ingests for dev

---

manifest.yaml

This is a known good version and we don't want to change it at the moment

Fix Mist to version currently on Prod

---

manifest.yaml

This reverts commit c3b4ee82af59bf8b733ea42e1bb005cc2e727794.

Revert "Switch mist branch (#1013)"

---

manifest.yaml

This reverts commit 9a558dca12e24e323cee7a4f583302a967d6a9f9.

Revert "Bump mist (#1042)"
